theme: jekyll-theme-cayman
description: "Aquest projecte té com objectiu permetre l'aprenentatge de les matemàtiques des del Batxillerat fins el primers cursos d'Universitat, 
seguint les publicacions del Professor Miquel Àngel Perelló."
email: "aprendespuntocom@gmail.com"


title: "aprendes.com"
plugins:
  - jekyll-pdf-embed
